### ISSUE TITLE
"prebuilt" not "prebuild"

### ISSUE THREAD

**Issue by Beliavsky** [awvwgk/mingw-w64-fpm-pkgbuild#1]
I think the readme.md should say "prebuilt" instead of "prebuild".

**Comment by awvwgk** [comment]
Nice catch, thanks.

**Comment by awvwgk** [comment]
Fixed in https://github.com/awvwgk/mingw-w64-fpm-pkgbuild/commit/37393ab5e5ee33ddd4fe3c90a09b6fc91fd3a156
